dbm-ui/backend/flow/utils/redis/redis_context_dataclass.py

fix(redis): redis_apply servers cal bug

---

dbm-services/common/db-resource/internal/config/config.go
dbm-services/common/db-resource/internal/controller/apply/apply.go
dbm-services/common/db-resource/internal/lock/redis_lock.go
dbm-services/common/db-resource/internal/lock/spinlock.go

fix read config bug

---

dbm-services/common/db-resource/internal/controller/manage/rs.go
dbm-services/common/db-resource/internal/controller/manage/rs_import.go

feat: add返回所有unused或使用中的资源

---

dbm-services/redis/db-tools/dbactuator/cmd/root.go
dbm-services/redis/db-tools/dbactuator/pkg/jobmanager/jobmanager.go
dbm-services/redis/db-tools/dbactuator/pkg/jobruntime/jobruntime.go

feat(redis): redis actuator  增加多进程并发控制支持,避免出现如下情况:N个实例下发N个actuator任务N个备份等任务同时运行的情况#219

feat(redis): redis actuator  增加多进程并发控制支持 #219

---

dbm-services/common/db-resource/internal/controller/apply/apply.go
dbm-services/common/db-resource/internal/controller/manage/rs_operation_info.go

fix:  count use limit offset error

fix: get resource opreation info count bug

---

dbm-services/mysql/db-tools/dbactuator/pkg/components/mysql/install_new_dbbackup.go
dbm-services/mysql/db-tools/mysql-crond/Makefile
dbm-services/mysql/db-tools/mysql-dbbackup/pkg/src/mysqlconn/conn.go
dbm-services/mysql/db-tools/mysql-dbbackup/pkg/src/spider/spider.go
dbm-services/mysql/db-tools/mysql-dbbackup/pkg/src/spider/spider_service.go
dbm-services/mysql/db-tools/mysql-monitor/pkg/itemscollect/masterslaveheartbeat/master_slave_heartbeat.go

fix(mysql): 修复 tendbcluster dbbackup 备份问题

---

dbm-services/common/dbha/ha-module/agent/monitor_agent.go
dbm-services/common/dbha/ha-module/constvar/constant.go
dbm-services/common/dbha/ha-module/dbmodule/mysql/MySQLProxy_switch.go
dbm-services/common/dbha/ha-module/dbmodule/mysql/MySQL_switch.go
dbm-services/common/dbha/ha-module/dbmodule/redis/predixy_switch.go
dbm-services/common/dbha/ha-module/dbmodule/redis/redis_switch.go
dbm-services/common/dbha/ha-module/dbmodule/redis/tendisplus_switch.go
dbm-services/common/dbha/ha-module/dbmodule/redis/twemproxy_switch.go
dbm-services/common/dbha/ha-module/gm/gcm.go
dbm-services/common/dbha/ha-module/gm/gmm.go
dbm-services/common/dbha/ha-module/gm/gqa.go
dbm-services/common/dbha/ha-module/log/log.go
dbm-services/common/dbha/ha-module/monitor/monitor.go
dbm-services/common/dbha/ha-module/util/timezone.go
dbm-services/common/dbha/ha-module/util/util.go

Fix macro style

---

dbm-ui/backend/flow/consts.py
dbm-ui/backend/flow/engine/bamboo/scene/redis/atom_jobs/redis_makesync.py
dbm-ui/backend/flow/utils/redis/redis_act_playload.py

fix tendis ssd switch backends

---

dbm-ui/backend/flow/consts.py
dbm-ui/backend/flow/engine/bamboo/scene/redis/atom_jobs/redis_shutdown.py
dbm-ui/backend/flow/engine/bamboo/scene/redis/redis_data_structure.py
dbm-ui/backend/flow/utils/redis/redis_act_playload.py

1、确保seg_range一一对应和构造部分实例时补充完twemproxy server信息
2、构造完成后tendisplus 集群meet构建

fix(redis): 确保seg_range一一对应和构造部分实例时补充完twemproxy server信息 close #411

---

dbm-ui/backend/flow/consts.py
dbm-ui/backend/flow/engine/bamboo/scene/redis/atom_jobs/redis_switch.py
dbm-ui/backend/flow/engine/bamboo/scene/redis/redis_cluster_scene_mss.py

fix(redis): 修复Redis 主从切换bug #461

fix(redis): 修复Redis 主从切换bug #461

---

dbm-ui/backend/flow/engine/bamboo/scene/redis/atom_jobs/redis_makesync.py
dbm-ui/backend/flow/engine/bamboo/scene/redis/redis_backend_scale.py

feat(redis): redis ssd scale #435

---

dbm-ui/backend/flow/engine/bamboo/scene/redis/redis_backend_scale.py

"resource_spec":{"backend_group":{}}  -> "resource_spec":{"master":{},"slave":{}}

fix(redis): redis扩缩容协议变更#453

---

dbm-ui/backend/db_meta/api/cluster/tendbcluster/remotedb_node_migrate.py
dbm-ui/backend/flow/consts.py
dbm-ui/backend/flow/engine/bamboo/scene/mysql/common/common_sub_flow.py
dbm-ui/backend/flow/engine/bamboo/scene/spider/spider_cluster_rollback_flow.py
dbm-ui/backend/flow/engine/bamboo/scene/spider/spider_recover.py
dbm-ui/backend/flow/engine/bamboo/scene/spider/spider_remote_node_migrate.py
dbm-ui/backend/flow/engine/bamboo/scene/spider/spider_remotedb_migrate_flow.py
dbm-ui/backend/flow/engine/bamboo/scene/spider/spider_remotedb_rebalance_flow.py
dbm-ui/backend/flow/engine/controller/spider.py
dbm-ui/backend/flow/urls.py
dbm-ui/backend/flow/utils/mysql/mysql_act_playload.py
dbm-ui/backend/flow/utils/spider/spider_db_meta.py
dbm-ui/backend/flow/utils/spider/tendb_cluster_info.py
dbm-ui/backend/flow/views/spider_migrage_remotedb.py
dbm-ui/backend/flow/views/tendb_cluster_remote_rebalance.py
dbm-ui/backend/flow/views/tendb_cluster_rollback_data.py

1、tendbcluster remote 节点扩缩容flow流程
2、tendbcluster remote 节点数据定点回档

feat: 开发tendbcluster remote节点扩缩容/remote节点定点回档 #308

---

dbm-services/mysql/db-tools/dbactuator/internal/subcmd/spiderctlcmd/cmd.go

fix(dbm-services):actuator

---

dbm-ui/backend/flow/utils/redis/redis_db_meta.py

fix(redis): 故障切换后, 旧实例角色为slave #585

fix(redis): 故障切换后, 旧实例角色为slave #585

---

dbm-services/mysql/db-partition/handler/handler.go
dbm-services/mysql/db-partition/service/manage_config.go

fix(db-partition):修复分区功能

---

dbm-services/mysql/db-tools/dbactuator/pkg/components/mysql/execute_partition_sql.go

fix(dbactuator):修改分区执行，兼容中控节点

---

dbm-ui/backend/components/mysql_backup/client.py
dbm-ui/backend/env/apigw_domains.py
dbm-ui/backend/flow/engine/bamboo/scene/mysql/common/exceptions.py
dbm-ui/backend/flow/engine/bamboo/scene/mysql/mysql_rollback_data_flow.py
dbm-ui/backend/flow/engine/bamboo/scene/mysql/mysql_rollback_data_sub_flow.py
dbm-ui/backend/flow/engine/bamboo/scene/spider/common/exceptions.py
dbm-ui/backend/flow/engine/bamboo/scene/spider/spider_cluster_rollback_flow.py
dbm-ui/backend/flow/engine/bamboo/scene/spider/spider_recover.py
dbm-ui/backend/flow/engine/bamboo/scene/spider/spider_remote_node_migrate.py
dbm-ui/backend/flow/engine/bamboo/scene/spider/spider_remotedb_rebalance_flow.py
dbm-ui/backend/flow/plugins/components/collections/mysql/mysql_download_backupfile.py
dbm-ui/backend/flow/plugins/components/collections/mysql/mysql_rollback_data_download_binlog.py
dbm-ui/backend/flow/utils/mysql/mysql_act_dataclass.py
dbm-ui/backend/flow/utils/mysql/mysql_act_playload.py

1、tendb 扩缩容优化代码
2、tendb 定点回档优化代码、binlog前滚接口调用修改
3、备份系统下载接口优化
4、mysql 定点回档子流程优化，修复bug

feat: 开发tendbcluster remote节点扩缩容/remote节点定点回档,优化mysql定点回档 #308

---

dbm-services/mysql/db-tools/dbactuator/pkg/components/mysql/execute_partition_sql.go

fix(dbactuator):分区部分修改pt工具执行命令

---

dbm-ui/backend/db_meta/enums/cluster_type.py
dbm-ui/backend/flow/engine/bamboo/scene/redis/redis_data_structure.py

refactor(redis): 代码风格统一和子任务规范化显示 close #693

---

dbm-services/mysql/db-tools/dbactuator/pkg/components/mysql/execute_partition_sql.go
dbm-services/mysql/db-tools/dbactuator/pkg/util/mysqlutil/mysqlclient_exec.go

fix(dbactuator):修复区初始化时中控专有的参数与普通参数无法一起设置问题

---

dbm-services/bigdata/db-tools/dbactuator/go.mod
dbm-services/bigdata/db-tools/dbactuator/go.sum
dbm-services/bigdata/db-tools/dbactuator/pkg/components/kafka/decom_broker.go
dbm-services/bigdata/db-tools/dbactuator/pkg/util/kafkautil/kafkautil.go
dbm-services/bigdata/db-tools/dbactuator/pkg/util/osutil/cmdexec.go

1.  About the partition reassignment, change of topic, from sequential migration to parallel migration
2.  Limit the speed rate to 30MB/s

refactor(kafka): Kafka shrink enhanced

---

dbm-ui/backend/flow/utils/redis/redis_module_operate.py

fix(redis): 兼容封装后的机器转移模块 close #746

---

dbm-ui/backend/flow/engine/bamboo/scene/redis/redis_backend_scale.py
dbm-ui/backend/flow/engine/bamboo/scene/redis/redis_cluster_apply_flow.py
dbm-ui/backend/flow/engine/bamboo/scene/redis/redis_proxy_scale.py
dbm-ui/backend/flow/engine/bamboo/scene/redis/tendis_plus_apply_flow.py
dbm-ui/backend/flow/utils/redis/redis_util.py

flow流程增加前置校验。涉及流程：
1、集群申请
2、proxy、backend扩缩容

perf(redis): redis flow增加pre-check close #716

---

dbm-ui/backend/db_meta/api/cluster/tendbcluster/remotedb_node_migrate.py
dbm-ui/backend/flow/engine/bamboo/scene/mysql/common/common_sub_flow.py
dbm-ui/backend/flow/engine/bamboo/scene/spider/common/common_sub_flow.py
dbm-ui/backend/flow/engine/bamboo/scene/spider/spider_cluster_rollback_flow.py
dbm-ui/backend/flow/engine/bamboo/scene/spider/spider_recover.py
dbm-ui/backend/flow/engine/bamboo/scene/spider/spider_remote_node_migrate.py
dbm-ui/backend/flow/engine/bamboo/scene/spider/spider_remotedb_rebalance_flow.py
dbm-ui/backend/flow/plugins/components/collections/mysql/mysql_download_backupfile.py
dbm-ui/backend/flow/plugins/components/collections/mysql/mysql_rollback_data_download_binlog.py
dbm-ui/backend/flow/utils/mysql/mysql_act_playload.py
dbm-ui/backend/flow/utils/mysql/mysql_context_dataclass.py
dbm-ui/backend/flow/utils/spider/spider_db_meta.py
dbm-ui/backend/flow/utils/spider/tendb_cluster_info.py

1、tendb cluster 扩缩容联调、bug修复、代码优化。
2、tendb cluster 定点回档联调、bug修复、代码优化。
3、db转移模块接口修复。

feat: remotedb 扩缩容,定点回档流程联调,fix bug,代码优化 #308

---

dbm-services/redis/db-tools/dbactuator/pkg/atomjobs/atomredis/redis_switch.go
dbm-ui/backend/db_meta/api/cluster/nosqlcomm/scale_tendis.py
dbm-ui/backend/db_meta/api/dbha/apis.py
dbm-ui/backend/db_meta/enums/cluster_entry_type.py
dbm-ui/backend/db_meta/flatten/proxy_instance.py
dbm-ui/backend/flow/engine/bamboo/scene/redis/atom_jobs/redis_cluster_master_rep.py
dbm-ui/backend/flow/engine/bamboo/scene/redis/atom_jobs/redis_cluster_slave_rep.py
dbm-ui/backend/flow/engine/bamboo/scene/redis/atom_jobs/redis_makesync.py
dbm-ui/backend/flow/engine/bamboo/scene/redis/atom_jobs/redis_shutdown.py
dbm-ui/backend/flow/engine/bamboo/scene/redis/atom_jobs/redis_switch.py
dbm-ui/backend/flow/utils/redis/redis_act_playload.py
dbm-ui/backend/flow/utils/redis/redis_db_meta.py

1.  切换/建Sync/下架兼容 Tendisplus
2. 修复重建热备娜模块bug
3. 增加整机替换、主故障替换兼容Tendisplus_

feat(redis): 原子任务兼容Tendisplus #629

---

dbm-ui/backend/flow/engine/bamboo/scene/redis/redis_data_structure.py
dbm-ui/backend/flow/engine/bamboo/scene/redis/redis_data_structure_task_delete.py

feat(redis): 在可执行文件和相关工具目录缺失时也支持构造销毁 close #801

---

dbm-ui/frontend/src/views/mysql/toolbox/components/ToolboxSide.vue
dbm-ui/frontend/src/views/redis/toolbox/components/ToolboxSide.vue

fix(frontend): redis工具箱自测问题 #855

---

dbm-services/bigdata/db-tools/dbactuator/pkg/components/kafka/install_kafka.go
dbm-ui/backend/flow/engine/bamboo/scene/kafka/kafka_scale_up_flow.py
dbm-ui/backend/flow/plugins/components/collections/kafka/kafka_config.py
dbm-ui/backend/flow/utils/kafka/kafka_act_playload.py

无认证集群部署支持。
新增流程参数no_security，1表示无认证。0表示认证，默认0。

feat(kafka): Support unsecurity cluster

---

dbm-services/common/celery-service/.gitignore
dbm-services/common/celery-service/Dockerfile
dbm-services/common/celery-service/Makefile
dbm-services/common/celery-service/collect/counter.sh
dbm-services/common/celery-service/external-tasks.yaml
dbm-services/common/celery-service/main.go
dbm-services/common/celery-service/pkg/config/init.go
dbm-services/common/celery-service/pkg/handler/internalhandler/democounter/counter.go
dbm-services/common/celery-service/readme.md

1. 完善了下docker build
2. 添加了4个和结果存储相关的环境变量
3. run子命令的大部分参数不再需要指定

fix(backend): celery task service 镜像打包

---

dbm-ui/frontend/src/components/tools-select-disable/hooks/useValidtor.ts
dbm-ui/frontend/src/components/tools-select-disable/index.vue
dbm-ui/frontend/src/services/model/redis/redis-host.ts
dbm-ui/frontend/src/views/redis/capacity-change/pages/page1/components/RenderTargetCapacity.vue
dbm-ui/frontend/src/views/redis/cluster-shard-update/pages/page1/components/RenderDeployPlan.vue
dbm-ui/frontend/src/views/redis/cluster-type-update/pages/page1/components/RenderDeployPlan.vue
dbm-ui/frontend/src/views/redis/common/instance-selector/components/RenderRedis.vue
dbm-ui/frontend/src/views/redis/common/instance-selector/components/RenderRedisFailHost.vue
dbm-ui/frontend/src/views/spider-manage/capacity-change/pages/page1/components/RenderData/RenderTargetResourceSpec.vue

fix(frontend): spider工具箱自测问题 #902
